version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: lacandelaria
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    image: tobiasriccone/backend-lacandelaria:latest
    container_name: backend
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      PROD_DB_URL: ${PROD_DB_URL}
      DB_PASSWORD: ${DB_PASSWORD}
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN}
      API_URL: ${API_URL}
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./images:/images

  frontend:
    image: tobiasriccone/frontend-lacandelaria:latest
    container_name: frontend
    restart: always

  nginx-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-manager
    restart: always
    ports:
      - "81:81"
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt

volumes:
  postgres-data: